### ISSUE TITLE
Deleting a shared workspace fails

### ISSUE THREAD

**Issue by daniellienert** [Sebobo/Shel.Neos.WorkspaceModule#13] opened 2022-09-08 12:18 UTC
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/642226/189119798-4f519e39-be17-4b45-a3c7-63c0008ed45b.png">

**Comment by Sebobo** [comment] 2022-09-09 08:03
Duplicate of #11 and it is already fixed in the `feature/acl` branch.

**Closed as completed by Sebobo** 2022-09-09 08:03 UTC
